<?php

namespace base\web;

use base\Request;
use base\Response;
use base\Server;

class Application extends Base
{
    /** @var Server */
    public $server;

    /** @var Request */
    public $request;

    /** @var Response */
    public $response;

    /**
     * @throws \base\exception\Exception
     */
    public function init()
    {
        $this->server   = $this->container->get(Server::class, ['data' => $_SERVER]);
        $this->request  = $this->container->get(Request::class, ['data' => [$_GET, $_POST]]);
        $this->response = $this->container->get(Response::class);
    }

    public function run()
    {
        /** @var $action \ReflectionMethod */
        list($controller, $action) = $this->getControllerActionName();
        if ($controller === null || $action === null) {
            $this->response->setStatusCode(404);
            $this->response->data = ['code' => 404, 'body' => Response::$httpStatuses['404']];
            $this->response->send();
            return;
        }
        $params = [];
        if ($action->getNumberOfParameters()) {
            foreach ($action->getParameters() as $parameter) {
                $paramsName = $parameter->getName();
                $value      = $this->request->getParams($paramsName);
                if ($value === null && $parameter->isDefaultValueAvailable()) {
                    $value = $parameter->getDefaultValue();
                }
                $params[] = $value;
            }
        }
        $result = $action->invokeArgs($controller, $params);
        if ($result instanceof Response) {
            $result->send();
        } else {
            $this->response->data = $result;
            $this->response->send();
        }
        return;
    }

    public function getControllerActionName()
    {
        $requestUri = trim($this->request->requestUri, '/');
        $aRequestUri = explode('/', $requestUri);
        list($controllerName, $actionName) = $aRequestUri;
        $this->controllerName = $controllerName ?: 'index';
        $this->actionName     = $actionName ?: 'index';
        return parent::getControllerActionName(); // TODO: Change the autogenerated stub
    }
}